#!/bin/bash

set -x -e -u -o pipefail

_main() {
	build_for_config build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBENCHMARK_ENABLE_TESTING=OFF
}

build_for_config() {
	local build_dir=$1
	local -a cmake_config=("${@:1}")
	cmake -GNinja "${cmake_config[@]}" -H. -B"${build_dir}"
	ninja -C "${build_dir}"
	"${build_dir}"/src/yo
}

_main "$@"
